on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: "A job to say Hello"
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: "Sayali"
    - name: Output
      run: echo "The time was ${{ steps.hello.outputs.time }}"